# Generated by Django 4.2.6 on 2023-10-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='max_adult_capacity',
            field=models.IntegerField(default=2, verbose_name='Capacidad máxima de adultos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='max_child_capacity',
            field=models.IntegerField(default=0, verbose_name='Capacidad máxima de niños'),
            preserve_default=False,
        ),
    ]
