# Generated by Django 4.2.6 on 2023-10-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rooms', '0002_remove_room_max_capacity_room_max_adult_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('Mantenimiento', 'Mantenimiento')], max_length=20, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
