# Generated by Django 4.2.6 on 2023-10-16 17:01

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('action', models.CharField(choices=[('Isert', 'Insert'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=10, verbose_name='Acción')),
                ('table_name', models.CharField(max_length=30, verbose_name='Nombre de la tabla')),
                ('detail', models.CharField(max_length=255, verbose_name='Detalles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
