# Generated by Django 4.2.6 on 2023-10-16 17:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha de salida')),
                ('num_adults', models.IntegerField(verbose_name='Número de adultos')),
                ('num_children', models.IntegerField(verbose_name='Número de niños')),
                ('total_price', models.IntegerField(verbose_name='Precio total')),
                ('status', models.CharField(max_length=40, verbose_name='Estado')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='BookingRoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('num_adults', models.IntegerField(verbose_name='Número de adultos')),
                ('num_children', models.IntegerField(verbose_name='Número de niños')),
                ('specific_price', models.IntegerField(verbose_name='Precio específico')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bookings.booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
            ],
            options={
                'verbose_name': 'Detalle de reservas',
                'verbose_name_plural': 'Detalles de reservas',
            },
        ),
    ]
