# Generated by Django 4.2.6 on 2023-10-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Confirmada', 'Confirmada'), ('En curso', 'En curso'), ('Terminada', 'Terminada'), ('Cancelada', 'Cancelada')], max_length=40, verbose_name='Estado'),
        ),
    ]
